Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Content-Type

### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Achmad",
    "email": "2110631170043@student.unsika.ac.id",
    "no_hp": "081298201276",
    "password": "#Pikri123"
}

### Verify
POST http://localhost:3000/api/v1/auth/verify
Content-Type: application/json

{
    "email": "2110631170043@student.unsika.ac.id",
    "otp": "677390"
}

### Get New OTP
PUT http://localhost:3000/api/v1/auth/verify/newOtp
Content-Type: application/json

{
    "email": "syofian.fikri@gmail.com"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "2110631170043@student.unsika.ac.id",
    "password": "#Pikri123"
}

### Forget Password
POST http://localhost:3000/api/v1/auth/forget-password
Content-Type: application/json

{
    "email" : "syofian.fikri@gmail.com"
}

### Reset Password
PUT http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN5b2ZpYW4uZmlrcmlAZ21haWwuY29tIiwiaWF0IjoxNzAyOTYzNTcyfQ.lhJJUj7eYRB3LvUqRG4oR41rdRrGc-AnPwEbckEezsQ
Content-Type: application/json

{
    "password": "#Pikri123",
    "password_confirmation": "#Pikri123"
}

### Get Me
GET http://localhost:3000/api/v1/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzAyOTg4MDY5fQ.OvklNR8a3fijIDnuqPhh7JXuLwmVA5Fo7ZRj-2ITFIQ



### Get All Categories List
GET http://localhost:3000/api/v1/categories?limit=10&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Categories Detail
GET http://localhost:3000/api/v1/categories/detail/3?limit=10&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json



### Get All Course List
GET http://localhost:3000/api/v1/course/list?limit=15&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Course Populer (Top 3 Course)
GET http://localhost:3000/api/v1/course/populer/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get All Populer Course (Top 6 Course)
GET http://localhost:3000/api/v1/course/populerall
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Course Detail
GET http://localhost:3000/api/v1/course/details/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Premium Course
GET http://localhost:3000/api/v1/course/premium?categoryId=1&level=Beginner&sortBy=populer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Free Course
GET http://localhost:3000/api/v1/course/free?categoryId=4&level=Intermediate&sortBy=populer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get All (Free & Prem) Course
GET http://localhost:3000/api/v1/course/all?categoryId=3&level=Advanced&sortBy=latest
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Search
GET http://localhost:3000/api/v1/course/search?name=web&limit=10&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Filter
GET http://localhost:3000/api/v1/course/filter?category=1&level=Beginner&limit=10&page=1&rating=true&terbaru=true
Content-Type: application/json

### Get User Enrollement
GET http://localhost:3000/api/v1/course/user-enrollement/?user=1&limit=10&page=1
Content-Type: application/json
GET http://localhost:3000/api/v1/course/search?name=science
Content-Type: application/json



### Update Profile
PUT http://localhost:3000/api/v1/accounts/updateprofile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: multipart/form-data

{
    "image": "https://ik.imagekit.io/livercourse/1702055226246_2_xswM7Y5.jpeg",
    "name": "Zaki Firdaus",
    "email": "zaki@gmail.com",
    "no_hp": "08928120390",
    "country": "Indonesia",
    "city": "Bandung"
}

### Update Password
PUT http://localhost:3000/api/v1/accounts/updatepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

{
    "password": "#Pikri123",
    "newPassword": "#Pikri123"
}

### Payment History
GET http://localhost:3000/api/v1/accounts/paymenthistory
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Notification
GET http://localhost:3000/api/v1/accounts/notification
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Dashboard Admin
GET http://localhost:3001/api/v1/admin/dashboard

### Kelola Kelas Admin
GET http://localhost:3001/api/v1/admin/kelolakelas

### Kelola Kelas Admin
DELETE http://localhost:3001/api/v1/admin/delete/1

