Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Content-Type

### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Pikri",
    "email": "syofian.fikri@gmail.com",
    "no_hp": "0891273213712",
    "password": "#Pikri123"
}

### Verify
POST http://localhost:3000/api/v1/auth/verify
Content-Type: application/json

{
    "email": "syofian.fikri@gmail.com",
    "otp": "884994"
}

### Get New OTP
PUT http://localhost:3000/api/v1/auth/verify/newOtp
Content-Type: application/json

{
    "email": "syofian.fikri@gmail.com"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "syofian.fikri@gmail.com",
    "password": "#Pikri123"
}

### Forget Password
POST http://localhost:3000/api/v1/auth/forget-password
Content-Type: application/json

{
    "email" : "syofian.fikri@gmail.com"
}

### Reset Password
PUT http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN5b2ZpYW4uZmlrcmlAZ21haWwuY29tIiwiaWF0IjoxNzAyOTYzNTcyfQ.lhJJUj7eYRB3LvUqRG4oR41rdRrGc-AnPwEbckEezsQ
Content-Type: application/json

{
    "password": "#Pikri123",
    "password_confirmation": "#Pikri123"
}

### Get Me
GET http://localhost:3000/api/v1/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzAzNTM0Mjc2fQ.ieXV1RR-WPHxFJ07o-hzF9PVU3UCQWIKGw_ICki-Mrc

### Get All Categories List
GET http://localhost:3000/api/v1/categories?limit=10&page=1
Content-Type: application/json

### Get Categories Detail
GET http://localhost:3000/api/v1/categories/detail/1?limit=10&page=1
Content-Type: application/json


### Get All Course List
GET http://localhost:3000/api/v1/course/list?limit=15&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Course Populer (Top 3 Course)
GET http://localhost:3000/api/v1/course/populer/1
Content-Type: application/json

### Get All Populer Course (Top 6 Course)
GET http://localhost:3000/api/v1/course/populerall
Content-Type: application/json

### Get User Course
GET http://localhost:3000/api/v1/course/user-enrollement
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzAzNTY2OTk5fQ.nyvHFaQhqCKHx2qiRD5ccKbh9TYpjyTG3JwdgFre5pw
Content-Type: application/json

### Get Course Detail
GET http://localhost:3000/api/v1/course/details/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzAzNjEzMDEyfQ.vuhNGzh13bKuAH0eQBqmNQQ-SPmK9j-Pi8L5oN4rOyg
Content-Type: application/json

### Add Rating
POST http://localhost:3000/api/v1/course/rating/1
Content-Type: application/json

{
    "rating": 2.0
}

### Get Course Detail
GET http://localhost:3001/api/v1/course/details/1

### Get Course Detail
POST http://localhost:3000/api/v1/course/updateisdone/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzAzNTY2OTk5fQ.nyvHFaQhqCKHx2qiRD5ccKbh9TYpjyTG3JwdgFre5pw
Content-Type: application/json

### Get Premium Course
GET http://localhost:3000/api/v1/course/premium?sortBy=latest
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Get Free Course
GET http://localhost:3000/api/v1/course/free?sortBy=latest
Content-Type: application/json

### Get All (Free & Prem) Course
GET http://localhost:3000/api/v1/course/all?sortBy=latest
Content-Type: application/json

### Get Search
GET http://localhost:3000/api/v1/course/search?name=microser
Content-Type: application/json

### Get Filter
GET http://localhost:3000/api/v1/course/filter?category=1&level=Beginner&limit=10&page=1&rating=true&terbaru=true
Content-Type: application/json

### Create Enrollment
POST http://localhost:3000/api/v1/enrollment/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzAzNTY2OTk5fQ.nyvHFaQhqCKHx2qiRD5ccKbh9TYpjyTG3JwdgFre5pw
Content-Type: application/json

{
    "metode_pembayaran": "creditCard",
    "card_number": 1111,
    "card_name": "BNI",
    "cvv": 123,
    "expired": "2022-10-05"
}

### Get By Enrollment
GET http://localhost:3000/api/v1/course/user-enrollement/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Update Profile
PUT http://localhost:3000/api/v1/accounts/updateprofile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: multipart/form-data

{
    "image": "https://ik.imagekit.io/livercourse/1702055226246_2_xswM7Y5.jpeg",
    "name": "Zaki Firdaus",
    "email": "zaki@gmail.com",
    "no_hp": "08928120390",
    "country": "Indonesia",
    "city": "Bandung"
}

### Update Password
PUT http://localhost:3000/api/v1/accounts/updatepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

{
    "password": "#Pikri123",
    "newPassword": "#Pikri123"
}

### Payment History
GET http://localhost:3000/api/v1/accounts/paymenthistory
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Notification
GET http://localhost:3000/api/v1/accounts/notification
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAyOTA5NzUzfQ.66RzvkwvngFogIULZFgyD3pTFfvE3PdQBMSZ5rAjn_0
Content-Type: application/json

### Dashboard Admin
GET http://localhost:3000/api/v1/admin/dashboard
Content-Type: application/json

### Kelola Kelas Admin, Contoh Response Pakai Filter (categoryId=4&level=Intermediate&type=isFree)
GET http://localhost:3000/api/v1/admin/kelolakelas?limit=10&page=1
Content-Type: application/json

### Delete
DELETE http://localhost:3000/api/v1/admin/course/4
Content-Type: application/json

### Login Admin
POST http://localhost:3000/api/v1/admin/login
Content-Type: application/json

{
    "id": 11,
    "password": "Admin_123"
}

### Create Category
POST http://localhost:3000/api/v1/admin/category
Content-Type: application/json

{
  "name": "Java",
  "image": "image java"
}

### Create Mentor
POST http://localhost:3000/api/v1/admin/mentor
Content-Type: application/json

{
    "name": "Rizal Akmal"
}

### Get All Mentor
GET http://localhost:3000/api/v1/admin/mentor?limit=10&page=1
Content-Type: application/json

### Create Course
POST http://localhost:3000/api/v1/admin/course
Content-Type: application/json

{
    "category_id": 4,
    "name": "Java blaba",
    "desc": "java balb abal adalah bla bla bla",
    "price": 100000,
    "level": "Beginner",
    "type": "isPremium",
    "intended_for": "1. Cocok untuk pemula yang belum memiliki keahlian desain sama sekali 2. Cocok untuk pemula yang ingin belajar UI Design 3. Cocok untuk designer yang ingin memperdalam style desain ilustrasi 4. Cocok untuk pemula yang ingin membuat ilustrasi dari basic hingga advance",
    "mentor_id": 8
}

### Update Course Admin
PUT http://localhost:3000/api/v1/admin/course/44
Content-Type: application/json

{
    "name": "HTML5 Dasar",
    "desc": "HTML5 adalah bahasa markup yang digunakan untuk membangun suatu tampilan pada Website. HTML5 ini peran nya seperti pondasi utama ketika Website sedang berada pada tahap Development. Ketika kita ingin membuat sebuah Header, Body, dan juga Footer pada Website maka kita perlu menggunakan bahasa markup ini. Kelas HTML5 dasar ini akan membawa kalian untuk berkenalan terlebih dahulu tentang bagaimana cara membangun suatu Website dengan mudah. Karena nanti pastinya kita juga akan mempelajari ilmu lebih dalam seperti menggunakan Framework CSS layaknya Bootstrap atau Bulma CSS. Pokoknya untuk kalian yang ingin belajar Web Development tapi masih bingung untuk memulainya dari mana maka jawabannya adalah kelas HTML5 Dasar ini. Silahkan bergabung karena kelas ini gratis untuk siapa saja.",
    "price": 0,
    "level": "Beginner",
    "type": "isFree",
    "intended_for": "1. Course ini diperuntukkan kepada pemula yang ingin mempelajari HTML 5 Dasar"
}

### Get All Course
GET http://localhost:3000/api/v1/admin/course?limit=10&page=1
Content-Type: application/json

### Create Chapter
POST http://localhost:3000/api/v1/admin/chapter
Content-Type: application/json

{
    "name": "Pendahuluan 2",
    "course_id": 26
}

### Get All Chapter
GET http://localhost:3000/api/v1/admin/chapter?limit=10&page=1
Content-Type: application/json

### Create Lesson
POST http://localhost:3000/api/v1/admin/lesson
Content-Type: application/json

{
    "name": "Apa lewsaosdas?",
    "video": "link_video_2",
    "desc": "di video kali ini bla bla bal",
    "duration": 4,
    "chapter_id": 7
}

###
GET http://localhost:3000/api/v1/course?search=course&is_premium=true&=popular
Content-Type: application/json
