openapi: 3.0.3
info:
  title: Liver MOOC (Massive Open Online Course)
  description: |-
    Dokumentasi ini menyediakan panduan lengkap untuk mengakses dan menggunakan API Liver MOOC (Massive Open Online Course). MOOC adalah platform pembelajaran daring yang menyediakan akses terbuka untuk berbagai kursus dari berbagai bidang, memungkinkan pengguna untuk belajar secara fleksibel sesuai dengan kebutuhan mereka.
    
    Rangkuman Fitur Utama:
    1. Daftar Kategori Kursus:
        - Endpoint: `/api/v1/categories`
        - Deskripsi: Mendapatkan daftar semua kategori kursus yang tersedia di Liver MOOC
        
    2. Detail Kategori dan Kursus:
        - Endpoint: `/api/v1/categories/detail/:id`
        - Deskripsi: Mendapatkan detail kategori tertentu beserta kursus yang terkait
        
    3.
  contact:
    email: syofian.fikri@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: Categories
    description: Operations related to Categories
paths:
  /categories:
    get:
      tags:
        - Categories
      operationId: get-fetch-all-categories
      summary: Get all categories
      description: Show all categories.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Number of items per page.
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number for pagination.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          pagination:
                            $ref: "#/components/schemas/Pagination"
                          categories:
                            type: array
                            items:
                              $ref: "#/components/schemas/CategoriesModel"
  "/categories/detail/{categoryId}":
    get:
      tags:
        - Categories
      operationId: get-fetch-categories-detail
      summary: Get categories details
      description: Retrieves details of a specific categories along with related courses.
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
          description: The ID of the user to retrieve.
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Number of items per page.
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number for pagination.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      status:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "Show Categories Detail"
                      data:
                        type: object
                        properties:
                          pagination:
                            $ref: "#/components/schemas/Pagination"
                          category:
                            $ref: "#/components/schemas/CategoriesDetailModel"
components:
  schemas:
    BasicResponse:
      title: BasicResponse
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: "success"
    CategoriesModel:
      title: Categories
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "UI/UX"
    CategoriesDetailModel:
      title: CategoriesDetail
      type: object
      properties:
        category_id:
          type: integer
          example: 13
        course_id:
          type: integer
          example: 20
        course:
          $ref: "#/components/schemas/CourseModel"
    CourseModel:
      title: Course
      type: object
      properties:
        id:
          type: integer
          example: 20
        name:
          type: string
          example: "Python Pemrograman Dasar"
    Pagination:
      title: Pagination
      type: object
      properties:
        links:
          type: object
          properties:
            next:
              type: string
              example: "https://domain.com/categories?limit=10&page=3"
            prev:
              type: string
              example: "https://domain.com/categories?limit=10&page=1"
        total_items:
          type: integer
          example: 100