name: Deploy to Railway (Dev)

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Packages
        run: npm install

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Run Migration for local Database
        run: railway run --service ${{ secrets.RAILWAY_SERVICE_ID }} npx prisma migrate deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}
      
      - name: Set Environment Variable for Shadow Database
        run: echo "SHADOW_DATABASE_URL=${secrets.SHADOW_DATABASE_URL}" >> .env

      - name: Run Migration for Shadow Database
        run: railway run --service ${{ secrets.RAILWAY_SERVICE_ID }} npx prisma migrate deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}